# Generated by Django 5.2.17 on 2026-10-02 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="invite_code",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
