# Generated by Django 5.2.17 on 2026-10-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fridge", "0001_initial"),
        ("households", "0002_household_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="household",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="households.household",
            ),
        ),
    ]
